-- =============================================================================
-- FIX_GAME_IDS.sql
-- Standardises all game_id values to the canonical format:
--   g_YYYY_MM_DD_HOMETEAM_AWAYTEAM
-- (e.g. g_2026_02_14_MET_BLD)
--
-- Run this in the Supabase SQL Editor.
-- It handles:
--   • UUIDs generated by the old admin UI (crypto.randomUUID())
--   • Malformed IDs with a venue prefix  (e.g. g_2026_02_01_EDI_CAS_HAI)
-- =============================================================================

-- Preview what will change (run this first to review):
SELECT
  game_id             AS old_id,
  'g_' || TO_CHAR(tipoff AT TIME ZONE 'Europe/Chisinau', 'YYYY_MM_DD')
        || '_' || home_team_id
        || '_' || away_team_id  AS new_id,
  home_team_id, away_team_id, tipoff
FROM games
WHERE game_id !~ '^g_\d{4}_\d{2}_\d{2}_[A-Z0-9]+_[A-Z0-9]+$';


-- =============================================================================
-- APPLY THE FIX
-- =============================================================================

-- Step 1: Update player_game_stats references BEFORE touching the games table
--         (avoids foreign-key violations if FK constraints exist)
WITH corrections AS (
  SELECT
    game_id AS old_id,
    'g_' || TO_CHAR(tipoff AT TIME ZONE 'Europe/Chisinau', 'YYYY_MM_DD')
          || '_' || home_team_id
          || '_' || away_team_id  AS new_id
  FROM games
  WHERE game_id !~ '^g_\d{4}_\d{2}_\d{2}_[A-Z0-9]+_[A-Z0-9]+$'
)
UPDATE player_game_stats pgs
SET game_id = c.new_id
FROM corrections c
WHERE pgs.game_id = c.old_id;

-- Step 2: Update the games table itself
WITH corrections AS (
  SELECT
    game_id AS old_id,
    'g_' || TO_CHAR(tipoff AT TIME ZONE 'Europe/Chisinau', 'YYYY_MM_DD')
          || '_' || home_team_id
          || '_' || away_team_id  AS new_id
  FROM games
  WHERE game_id !~ '^g_\d{4}_\d{2}_\d{2}_[A-Z0-9]+_[A-Z0-9]+$'
)
UPDATE games g
SET game_id = c.new_id
FROM corrections c
WHERE g.game_id = c.old_id;

-- Step 3: Verify — this should return zero rows if all IDs are now correct
SELECT game_id FROM games
WHERE game_id !~ '^g_\d{4}_\d{2}_\d{2}_[A-Z0-9]+_[A-Z0-9]+$';
