-- Generated by scripts/reconcile-rosters.mjs after dry-run preflight.
-- Review this file in full. Execute only in Supabase SQL Editor.
BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';

DO $reconcile$
DECLARE
  target RECORD;
  existing RECORD;
  canonical_id TEXT;
  duplicate_id TEXT;
  next_number INTEGER;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.seasons WHERE season = '2026/27') THEN
    RAISE EXCEPTION 'Missing required season 2026/27';
  END IF;
  IF (SELECT COUNT(*) FROM public.teams WHERE team_id IN ('COM', 'CN2', 'AMB', 'CAS', 'ADM', 'BRI', 'BLD')) <> 7 THEN
    RAISE EXCEPTION 'One or more required team IDs are missing or duplicated';
  END IF;

  CREATE TEMP TABLE _recon_targets (
    team_id TEXT NOT NULL,
    canonical_name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT NOT NULL,
    PRIMARY KEY (team_id, canonical_name)
  ) ON COMMIT DROP;

  INSERT INTO _recon_targets (team_id, canonical_name, first_name, last_name) VALUES
    ('COM', 'Vladimir Dimoglo', 'Vladimir', 'Dimoglo'),
    ('COM', 'Daniil Dimitroglo', 'Daniil', 'Dimitroglo'),
    ('COM', 'Maxim Dudoglo', 'Maxim', 'Dudoglo'),
    ('COM', 'Roman Barladean', 'Roman', 'Barladean'),
    ('COM', 'Victor Leiciu', 'Victor', 'Leiciu'),
    ('COM', 'Arteom Zlatov', 'Arteom', 'Zlatov'),
    ('COM', 'Nichita Ivanenco', 'Nichita', 'Ivanenco'),
    ('COM', 'Roman Diulgher', 'Roman', 'Diulgher'),
    ('COM', 'Petru Constantinov', 'Petru', 'Constantinov'),
    ('COM', 'Nicolai Topal', 'Nicolai', 'Topal'),
    ('COM', 'Stepan Peadisev', 'Stepan', 'Peadisev'),
    ('COM', 'Alexandr Barladean', 'Alexandr', 'Barladean'),
    ('COM', 'Vadim Cilcic', 'Vadim', 'Cilcic'),
    ('CN2', 'Alexandr Harevschi', 'Alexandr', 'Harevschi'),
    ('CN2', 'Alic Tonciu', 'Alic', 'Tonciu'),
    ('CN2', 'Genadii Kuceriavii', 'Genadii', 'Kuceriavii'),
    ('AMB', 'Ion Golovco', 'Ion', 'Golovco'),
    ('AMB', 'Nichita Visneacov', 'Nichita', 'Visneacov'),
    ('CAS', 'Semen Goldstein', 'Semen', 'Goldstein'),
    ('CAS', 'Danila Kravchenko', 'Danila', 'Kravchenko'),
    ('CAS', 'Martin Arzumanian', 'Martin', 'Arzumanian'),
    ('CAS', 'Stanislav Goldstein', 'Stanislav', 'Goldstein'),
    ('ADM', 'Alexei Turcanu', 'Alexei', 'Turcanu'),
    ('ADM', 'Stefan Placinta', 'Stefan', 'Placinta'),
    ('ADM', 'Bogdan Gutu', 'Bogdan', 'Gutu');

  FOR target IN SELECT * FROM _recon_targets LOOP
    SELECT p.* INTO existing
    FROM public.players p
    WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower(target.canonical_name)
       OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower(target.canonical_name)
       OR (lower(coalesce(p.first_name, '')) = lower(left(target.first_name, 1)) AND lower(p.last_name) = lower(target.last_name));
    IF FOUND THEN
      SELECT COUNT(*) INTO next_number
      FROM public.players p
      WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower(target.canonical_name)
         OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower(target.canonical_name)
         OR (lower(coalesce(p.first_name, '')) = lower(left(target.first_name, 1)) AND lower(p.last_name) = lower(target.last_name));
      IF next_number > 1 THEN RAISE EXCEPTION 'Ambiguous player identity: %', target.canonical_name; END IF;
      canonical_id := existing.player_id;
      UPDATE public.players SET first_name = target.first_name, last_name = target.last_name WHERE player_id = canonical_id;
    ELSE
      SELECT COALESCE(MAX((substring(player_id FROM 2))::INTEGER), 0) + 1 INTO next_number
      FROM public.players WHERE player_id ~ '^p[0-9]+$';
      canonical_id := 'p' || lpad(next_number::TEXT, 4, '0');
      INSERT INTO public.players (player_id, team_id, first_name, last_name, jersey_number, photo_url)
      VALUES (canonical_id, target.team_id, target.first_name, target.last_name, NULL, NULL);
    END IF;
    INSERT INTO public.player_seasons (player_id, season, team_id, jersey_number, is_active)
    VALUES (canonical_id, '2026/27', target.team_id, (SELECT jersey_number FROM public.players WHERE player_id = canonical_id), true)
    ON CONFLICT (player_id, season) DO UPDATE SET team_id = EXCLUDED.team_id, is_active = true;
    UPDATE public.players SET team_id = target.team_id WHERE player_id = canonical_id;
  END LOOP;

  -- Explicitly reconnect the six abbreviated COM identities before any cleanup.
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Leonid G', 1)) AND lower(p.last_name) = lower(split_part('Leonid G', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Leonid Gherciu-Peev') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Leonid Gherciu-Peev');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Leonid G'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Leonid', last_name = 'Gherciu-Peev' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Arthur P', 1)) AND lower(p.last_name) = lower(split_part('Arthur P', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Artur Popovici') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Artur Popovici');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Arthur P'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Artur', last_name = 'Popovici' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Denis R', 1)) AND lower(p.last_name) = lower(split_part('Denis R', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Denis Rozengravt') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Denis Rozengravt');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Denis R'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Denis', last_name = 'Rozengravt' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Ivan+0 D', 1)) AND lower(p.last_name) = lower(split_part('Ivan+0 D', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Ivan Dologlu') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Ivan Dologlu');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Ivan+0 D'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Ivan', last_name = 'Dologlu' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Mix K', 1)) AND lower(p.last_name) = lower(split_part('Mix K', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Mihail Cristov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Mihail Cristov');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Mix K'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Mihail', last_name = 'Cristov' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(coalesce(p.first_name, '')) = lower(left('Serghei G', 1)) AND lower(p.last_name) = lower(split_part('Serghei G', ' ', 2));
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Serghei Garciu') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Serghei Garciu');
  IF duplicate_id IS NULL THEN RAISE EXCEPTION 'Missing temporary COM identity: %', 'Serghei G'; END IF;
  IF canonical_id IS NULL THEN
    canonical_id := duplicate_id;
    UPDATE public.players SET first_name = 'Serghei', last_name = 'Garciu' WHERE player_id = canonical_id;
  END IF;
  IF duplicate_id <> canonical_id THEN UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id; END IF;
  INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'COM', true) ON CONFLICT (player_id, season) DO UPDATE SET team_id = 'COM', is_active = true;
  UPDATE public.players SET team_id = 'COM' WHERE player_id = canonical_id;

  -- Preserve history while moving confirmed 2026/27 memberships.
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Nichita Visneacov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Nichita Visneacov');
  IF canonical_id IS NULL THEN RAISE EXCEPTION 'Missing transfer player: %', 'Nichita Visneacov'; END IF;
  UPDATE public.player_seasons SET team_id = 'AMB', is_active = true WHERE player_id = canonical_id AND season = '2026/27';
  IF NOT FOUND THEN INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'AMB', true); END IF;
  UPDATE public.players SET team_id = 'AMB' WHERE player_id = canonical_id;
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Ion Golovco') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Ion Golovco');
  IF canonical_id IS NULL THEN RAISE EXCEPTION 'Missing transfer player: %', 'Ion Golovco'; END IF;
  UPDATE public.player_seasons SET team_id = 'AMB', is_active = true WHERE player_id = canonical_id AND season = '2026/27';
  IF NOT FOUND THEN INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'AMB', true); END IF;
  UPDATE public.players SET team_id = 'AMB' WHERE player_id = canonical_id;
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Stanislav Goldstein') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Stanislav Goldstein');
  IF canonical_id IS NULL THEN RAISE EXCEPTION 'Missing transfer player: %', 'Stanislav Goldstein'; END IF;
  UPDATE public.player_seasons SET team_id = 'CAS', is_active = true WHERE player_id = canonical_id AND season = '2026/27';
  IF NOT FOUND THEN INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'CAS', true); END IF;
  UPDATE public.players SET team_id = 'CAS' WHERE player_id = canonical_id;
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Alic Tonciu') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Alic Tonciu');
  IF canonical_id IS NULL THEN RAISE EXCEPTION 'Missing transfer player: %', 'Alic Tonciu'; END IF;
  UPDATE public.player_seasons SET team_id = 'CN2', is_active = true WHERE player_id = canonical_id AND season = '2026/27';
  IF NOT FOUND THEN INSERT INTO public.player_seasons (player_id, season, team_id, is_active) VALUES (canonical_id, '2026/27', 'CN2', true); END IF;
  UPDATE public.players SET team_id = 'CN2' WHERE player_id = canonical_id;

  -- Apply canonical renames and then merge only explicitly confirmed duplicates.
  UPDATE public.players p SET first_name = split_part('Daniel Chislin', ' ', 1), last_name = substring('Daniel Chislin' FROM position(' ' IN 'Daniel Chislin') + 1) WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Chislih') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Chislih');
  UPDATE public.players p SET first_name = split_part('Veaceslav Dronnicov', ' ', 1), last_name = substring('Veaceslav Dronnicov' FROM position(' ' IN 'Veaceslav Dronnicov') + 1) WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('V Dronicov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('V Dronicov');
  UPDATE public.players p SET first_name = split_part('Alexandr Kalashnikov', ' ', 1), last_name = substring('Alexandr Kalashnikov' FROM position(' ' IN 'Alexandr Kalashnikov') + 1) WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Kalashnikov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Kalashnikov');
  UPDATE public.players p SET first_name = split_part('Stanislav Goldstein', ' ', 1), last_name = substring('Stanislav Goldstein' FROM position(' ' IN 'Stanislav Goldstein') + 1) WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('S Golistein') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('S Golistein');
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('A Harevschii') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('A Harevschii');
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Alexandr Harevschi') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Alexandr Harevschi');
  IF duplicate_id IS NOT NULL AND canonical_id IS NOT NULL AND duplicate_id <> canonical_id THEN
    UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id;
    UPDATE public.player_seasons ps SET player_id = canonical_id WHERE ps.player_id = duplicate_id AND NOT EXISTS (SELECT 1 FROM public.player_seasons keep WHERE keep.player_id = canonical_id AND keep.season = ps.season);
    UPDATE public.player_seasons SET is_active = false WHERE player_id = duplicate_id;
  END IF;
  SELECT p.player_id INTO duplicate_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('G ComnatnIi') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('G ComnatnIi');
  SELECT p.player_id INTO canonical_id FROM public.players p WHERE lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Gleb Comnotnii') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Gleb Comnotnii');
  IF duplicate_id IS NOT NULL AND canonical_id IS NOT NULL AND duplicate_id <> canonical_id THEN
    UPDATE public.player_game_stats SET player_id = canonical_id WHERE player_id = duplicate_id;
    UPDATE public.player_seasons ps SET player_id = canonical_id WHERE ps.player_id = duplicate_id AND NOT EXISTS (SELECT 1 FROM public.player_seasons keep WHERE keep.player_id = canonical_id AND keep.season = ps.season);
    UPDATE public.player_seasons SET is_active = false WHERE player_id = duplicate_id;
  END IF;

  -- Confirmed removals are inactive only; records and statistics remain.
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'CN2' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('A Streapko') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('A Streapko') OR lower(coalesce(p.first_name, '')) = lower(left('A Streapko', 1)) AND lower(p.last_name) = lower(split_part('A Streapko', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('M Solosciuc') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('M Solosciuc') OR lower(coalesce(p.first_name, '')) = lower(left('M Solosciuc', 1)) AND lower(p.last_name) = lower(split_part('M Solosciuc', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('V Juganaru') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('V Juganaru') OR lower(coalesce(p.first_name, '')) = lower(left('V Juganaru', 1)) AND lower(p.last_name) = lower(split_part('V Juganaru', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('V Arnaut') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('V Arnaut') OR lower(coalesce(p.first_name, '')) = lower(left('V Arnaut', 1)) AND lower(p.last_name) = lower(split_part('V Arnaut', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Grosu') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Grosu') OR lower(coalesce(p.first_name, '')) = lower(left('D Grosu', 1)) AND lower(p.last_name) = lower(split_part('D Grosu', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('K Osjovschi') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('K Osjovschi') OR lower(coalesce(p.first_name, '')) = lower(left('K Osjovschi', 1)) AND lower(p.last_name) = lower(split_part('K Osjovschi', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'AMB' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('B Bejinari') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('B Bejinari') OR lower(coalesce(p.first_name, '')) = lower(left('B Bejinari', 1)) AND lower(p.last_name) = lower(split_part('B Bejinari', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'CAS' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Pavel Tibrigan') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Pavel Tibrigan') OR lower(coalesce(p.first_name, '')) = lower(left('Pavel Tibrigan', 1)) AND lower(p.last_name) = lower(split_part('Pavel Tibrigan', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'CAS' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Alexandr Ceaicovschii') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Alexandr Ceaicovschii') OR lower(coalesce(p.first_name, '')) = lower(left('Alexandr Ceaicovschii', 1)) AND lower(p.last_name) = lower(split_part('Alexandr Ceaicovschii', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'CAS' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Vladislav Solopa') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Vladislav Solopa') OR lower(coalesce(p.first_name, '')) = lower(left('Vladislav Solopa', 1)) AND lower(p.last_name) = lower(split_part('Vladislav Solopa', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('F Rodion') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('F Rodion') OR lower(coalesce(p.first_name, '')) = lower(left('F Rodion', 1)) AND lower(p.last_name) = lower(split_part('F Rodion', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Alexei') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Alexei') OR lower(coalesce(p.first_name, '')) = lower(left('D Alexei', 1)) AND lower(p.last_name) = lower(split_part('D Alexei', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('A Gincul') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('A Gincul') OR lower(coalesce(p.first_name, '')) = lower(left('A Gincul', 1)) AND lower(p.last_name) = lower(split_part('A Gincul', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('M Cernei') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('M Cernei') OR lower(coalesce(p.first_name, '')) = lower(left('M Cernei', 1)) AND lower(p.last_name) = lower(split_part('M Cernei', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Corobcov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Corobcov') OR lower(coalesce(p.first_name, '')) = lower(left('D Corobcov', 1)) AND lower(p.last_name) = lower(split_part('D Corobcov', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('A Covaliucuc') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('A Covaliucuc') OR lower(coalesce(p.first_name, '')) = lower(left('A Covaliucuc', 1)) AND lower(p.last_name) = lower(split_part('A Covaliucuc', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('N Vitneanschii') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('N Vitneanschii') OR lower(coalesce(p.first_name, '')) = lower(left('N Vitneanschii', 1)) AND lower(p.last_name) = lower(split_part('N Vitneanschii', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('A Dragomir') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('A Dragomir') OR lower(coalesce(p.first_name, '')) = lower(left('A Dragomir', 1)) AND lower(p.last_name) = lower(split_part('A Dragomir', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('D Mihai') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('D Mihai') OR lower(coalesce(p.first_name, '')) = lower(left('D Mihai', 1)) AND lower(p.last_name) = lower(split_part('D Mihai', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('G Alexandr') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('G Alexandr') OR lower(coalesce(p.first_name, '')) = lower(left('G Alexandr', 1)) AND lower(p.last_name) = lower(split_part('G Alexandr', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'ADM' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('V Matco') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('V Matco') OR lower(coalesce(p.first_name, '')) = lower(left('V Matco', 1)) AND lower(p.last_name) = lower(split_part('V Matco', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'BRI' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Alic Tonciu') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Alic Tonciu') OR lower(coalesce(p.first_name, '')) = lower(left('Alic Tonciu', 1)) AND lower(p.last_name) = lower(split_part('Alic Tonciu', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'BRI' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Nichita Visneacov') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Nichita Visneacov') OR lower(coalesce(p.first_name, '')) = lower(left('Nichita Visneacov', 1)) AND lower(p.last_name) = lower(split_part('Nichita Visneacov', ' ', 2))));
  UPDATE public.player_seasons ps SET is_active = false WHERE ps.season = '2026/27' AND ps.team_id = 'BRI' AND EXISTS (SELECT 1 FROM public.players p WHERE p.player_id = ps.player_id AND (lower(concat_ws(' ', p.first_name, p.last_name)) = lower('Stanislav Goldstein') OR lower(concat_ws(' ', p.last_name, p.first_name)) = lower('Stanislav Goldstein') OR lower(coalesce(p.first_name, '')) = lower(left('Stanislav Goldstein', 1)) AND lower(p.last_name) = lower(split_part('Stanislav Goldstein', ' ', 2))));

  INSERT INTO public.team_season_coaches (team_id, season, coach_name)
  VALUES ('BLD', '2026/27', 'Artur Tonciu')
  ON CONFLICT (team_id, season) DO UPDATE SET coach_name = EXCLUDED.coach_name;
END;
$reconcile$;

DO $$
BEGIN
  IF EXISTS (SELECT player_id, season, team_id FROM public.player_seasons WHERE is_active GROUP BY player_id, season, team_id HAVING COUNT(*) > 1) THEN RAISE EXCEPTION 'Duplicate active membership detected'; END IF;
  IF EXISTS (SELECT pgs.game_id, pgs.player_id, pgs.team_id FROM public.player_game_stats pgs JOIN public.games g ON g.game_id = pgs.game_id WHERE g.season = '2026/27' GROUP BY pgs.game_id, pgs.player_id, pgs.team_id HAVING COUNT(*) > 1) THEN RAISE EXCEPTION 'Duplicate statistics rows detected'; END IF;
  IF EXISTS (SELECT pgs.player_id FROM public.player_game_stats pgs JOIN public.games g ON g.game_id = pgs.game_id WHERE g.season = '2026/27' AND NOT EXISTS (SELECT 1 FROM public.player_seasons ps WHERE ps.player_id = pgs.player_id AND ps.season = '2026/27' AND ps.team_id = pgs.team_id)) THEN RAISE EXCEPTION 'Statistics row has no corresponding season membership'; END IF;
END $$;

COMMIT;
